steps:
  - id: Get Gke Cluster
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud container clusters list --project coen-jeronimo-garcia

steps:
  - id: Do i have kuebctl
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        kubectl
options:
  pool:
    name: 'projects/745198875057/locations/europe-west2/workerPools/pool'
