steps:
  - id: Get Gke Cluster
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials cloudbuild3 --zone europe-west2-a --project coen-jeronimo-garcia
  - id: kubectl
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -c
      - |
        kubectl get all -A

options:
  pool:
    name: 'projects/745198875057/locations/europe-west2/workerPools/pool'
